added condition for sub step

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -7,9 +7,12 @@ jobs:
         steps:
             - name: Step 1
               run:  sleep 20
+            - name: Step 2
+              id: step-2
+              run: exit 1
             - name: Runs on Failure
-              if: failure()
-              run: echo "Job Failed"
+              if: failure() && steps.step-2.conclusion == 'failure' # was if: failure()
+              run: echo "Step 2 has failed"
             - name: Runs on Success
               if: success() # not needed (DEFAULT BEHAVIOR)
               run: echo "Runs on Success"
@@ -25,5 +28,5 @@ jobs:
         needs: job-1
         if: failure()
         steps:
-            - name: Checkout
+            - name: Runs on Failure
               run: echo 'Job 2'
